### ISSUE TITLE
after use, console appears $attrs is readonly and $listeners is readonly error

### ISSUE THREAD

**Issue by wangjue666** [dwatts3624/vue-keep-alive-dev#1]
![1600158319(1)](https://user-images.githubusercontent.com/24707417/93185573-2822f980-f770-11ea-9c9f-a20c88d2de8c.jpg)

```
  <div class="d2-theme-container-main-body" flex-box="1">
         <transition :name="transitionActive ? 'fade-transverse' : ''">
              <keep-alive :include="keepAlive">
                    <router-view :key="$route.path + $route.meta[$route.path]" />
               </keep-alive>
        </transition>
</div>
```

vue version  2.6.11

project is  https://github.com/d2-projects/d2-admin

Can you give me some advice?

**Comment by dwatts3624** [comment]
Hi @wangjue666 I'm running the same Vue version and haven't seen that error so I'll take a look at your project specifically to see if I can trace that down.

**Comment by wangjue666** [comment]
@dwatts3624  Thank you bro, I look forward to your reply :smiley:   You can also submit a pull request
